name: Publish to NPM

# Runs when a tag like v1.2.3 is pushed
on:
    push:
        tags:
            - "v*.*.*"
    workflow_dispatch:

# GitHub Actions example
jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write # For git operations
            id-token: write # REQUIRED FOR OIDC
        env:
            TMDB_ACCESS_TOKEN: ${{ secrets.TMDB_ACCESS_TOKEN }}

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

              # Install pnpm
            - uses: pnpm/action-setup@v4
              with:
                  version: 8.8.0
                  run_install: false

            - uses: actions/setup-node@v5
              with:
                  node-version: "20"
                  registry-url: "https://registry.npmjs.org"
                  cache: pnpm

            # Update npm for OIDC publishing compatibility
            - run: npm install -g npm@11.5.1

            - name: Configure git identity
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

            # Install dependencies with pnpm
            - run: pnpm install --frozen-lockfile

            # Run release
            - run: pnpm exec release-it --ci
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
